urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

import main.feeds

admin.autodiscover()

feeds = {'latest': main.feeds.LatestEntries}

urlpatterns = patterns('',
    (r'^admin/(.*)', admin.site.root),

    (r'^category/(?P<slug>.*).html$', 'catalog.views.show_category'),
    (r'^host/(?P<slug>.*).html$', 'catalog.views.show_host'),
    (r'^hosts/(?P<slug>.*).html$', 'catalog.views.show_category'),
    (r'^hosts.html$', 'catalog.views.show_categories'),

    (r'^leaderboard.html$', 'catalog.views.leaderboard'),
    (r'^matrix.html$', 'catalog.views.matrix'),
    (r'^visit/(?P<slug>.*).html$', 'catalog.views.visit'),

    (r'^comment/helpful/(?P<id>.*).html$', 'catalog.views.helpful'),
    (r'^comment/report/(?P<id>.*).html$', 'catalog.views.report'),

    (r'^sitemap.html$', 'catalog.views.sitemap'),
    (r'^sitemap.xml$', 'catalog.views.sitemap_xml'),
    
    (r'^blog.html$', 'main.views.show_blog'),
    (r'^faq.html$', 'main.views.show_faq'),
    (r'^article/(?P<slug>.*).html$', 'main.views.show_entry'),
    (r'^articles.html$', 'main.views.show_entries'),

    (r'^test.html$', 'catalog.views.test'),

    (r'^alt_index.html$', 'main.views.alt_index'),
    (r'^$|index.html$', 'main.views.index'),

    (r'^feeds/(?P<url>.*).xml$', 'django.contrib.syndication.views.feed',
        {'feed_dict': feeds}),

    (r'^(?P<slug>(.*)).html', 'main.views.get_page'),
)

main/models.py
import datetime
import base64
import re

from django.db import models
from django.contrib.auth import models as auth

def slugify(data):
    """Turn a piece of data into a slug"""

    data = data.lower()
    data = re.sub('\s+', '-', data)
    return re.sub('[^a-z0-9\-]', '', data)

class Common(models.Model):
    """Common base for handling things like saving slugs.
    We don't put fields in here because Django puts those in seperate
    tables (sometimes?)."""

    class Meta:
        abstract = True

    def save(self):
        if hasattr(self, 'slug'):
            if self.slug is None or len(self.slug.strip()) == 0:
                self.slug = slugify(self.name)

        super(Common, self).save()


class Page(Common):
    """Store abitrary pages like About/Privacy/TOS in the database for easy updating"""
    name = models.CharField(max_length=255)
    slug = models.SlugField('Slug', max_length=255, unique=True)
    text = models.TextField()

    def __unicode__(self):
        return "/%s.html - %s" % (self.slug, self.name)

class Email(models.Model):
    """Emails gathered for the newsletter"""

    value = models.EmailField(max_length=255, unique=True)
    ip = models.CharField(max_length=25)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.value


class Entry(Common):
    """Blog Entry"""

    name = models.CharField(max_length=255)
    user = models.ForeignKey(auth.User, default=1)
    slug = models.SlugField(unique=True, default=None, blank=True)
    text = models.TextField()

    pub_date = models.DateTimeField(default=datetime.datetime.now())

    def __unicode__(self):
        return "%s - %s" % (self.name, self.user)

    def get_absolute_url(self):
        return "http://hosting-choice.com/article/%s.html" % self.slug


class FAQ(Common):
    """Frequently Asked Question"""

    question = models.CharField(max_length=255)
    answer = models.TextField()

    order = models.IntegerField(default=0)

    def __unicode__(self):
        return self.question

catalog/forms.py
from django import forms

import models

class CommentForm(forms.Form):

    name = forms.CharField(max_length=255,
        widget=forms.TextInput(attrs={'tabindex': 1}))

    email = forms.EmailField(max_length=255,
        widget=forms.TextInput(attrs={'tabindex': 2}))

    website = forms.URLField(required=False, max_length=255,
        widget=forms.TextInput(attrs={'tabindex': 3}))

    text = forms.CharField(
        widget=forms.widgets.Textarea(attrs={
            'rows':15, 'cols':52, 'tabindex': 4}))

    rating_features_val = forms.IntegerField(widget=forms.HiddenInput(),
        initial=-1)
    rating_uptime_val = forms.IntegerField(widget=forms.HiddenInput(),
        initial=-1)
    rating_support_val = forms.IntegerField(widget=forms.HiddenInput(),
        initial=-1)

class LeadForm(forms.ModelForm):

    class Meta:
        model = models.Lead

templates/category.html
{% extends 'base.html' %}

{% block body %}
    <div id="category">
        {% if category %}
            <h1>{{category.name}}</h1>
            <p class="desc">{{category.description}}</p>
            <h2>Hosts in {{category.name}}</h2>
            <ul>
                {% for host in hosts %}

                    <a href="/host/{{host.slug}}.html">{{host.name}}</a>
                    <span>{{host.url}}</span>
                    <em>({{host.user}} - {{host.hits}} hits)</em>
                    <p>{{host.description}}</p>
                {% endfor %}
            </ul>
        {% else %}
            <h1>Cannot find category</h1>
        {% endif %}
    </div>
{% endblock %}

templates/comment_form.html
<a name="comment-form" />
<div id="comment-form-{{host.id}}" class="comment-form">
   <h3>Create A New Review For Idologic</h3>
    <p>Do you have experience using
    <strong>{{host.name}} Web Hosting</strong>?
    Write a review for <strong>{{host.name}}</strong> 
    below. Be sure to rate your experiience so others know what to expect from
    <strong>{{host.name}} hosting</strong>.</p>

    <form action="/host/{{host.slug}}.html" method="POST">
        {{ form.rating_features_val }}
        {{ form.rating_uptime_val }}
        {{ form.rating_support_val }}
        <table cellspacing="0">
            <tr>
                <th><label for="id_name">Name:</label></th>
                <td>
                    {{ form.name }}
                    {{ form.name.errors }}
                </td>
                <th><label for="id_rating_features">Features:</label></th>
                <td>
                    <div id="id_rating_features" class="rating"></div>
                </td>
            </tr>
            <tr>
                <th><label for="id_email">Email:</label></th>
                <td>
                    {{ form.email }}
                    {{ form.email.errors }}
                </td>
                <th><label for="id_rating_uptime">Uptime:</label></th>
                <td>
                    <div id="id_rating_uptime" class="rating"></div>
                </td>
            </tr>
            <tr>
                <th class="optional"><label for="id_website">Website</label>:</th>
                <td>
                    {{ form.website }}
                    <small>(Optional)</small>
                    {{ form.website.errors }}
                </td>
                <th><label for="id_rating_support">Support:</label></th>
                <td>
                    <div id="id_rating_support" class="rating"></div>
                </td>
            </tr>
            <tr>
                <th class="textarea"><label for="id_text">Review:</label></th>
                <td colspan="3">
                    {{ form.text }}
                    <br /><small>Simple HTML is allowed,
                        &lt;b&gt;, &lt;i&gt;, &lt;u&gt;, &lt;p&gt;.</small>
                    {{ form.text.errors }}
                </td>
            </tr>
            <tr>
                <th></th>
                <td colspan="3">
                    <input tabindex="5" type="submit" />
                </td>
            </tr>
        </table>
    </form>



</div>

templates/comments.html
<a name="comments" />
<div id="comments-{{host.id}}" class="comments">
    <h2><span class="icon"></span>{{ host.comments() | length }} {{host.name}} Web Hosting Reviews</h2>

    <ul id="review-list">

        {% for comment in host.comments() %}
        <li class="
            {%- call macros.get_rating_mood(comment.rating()) -%}
                comment
            {%- endcall -%}">
                <div class="meta">
                    <span class="author">
                        <span class="name">
                            {% if comment.website %}
                                <a href="{{comment.website}}">
                                    {{comment.name}}
                                </a>
                            {% else %}
                                {{comment.name}}
                            {% endif %}
                        </span> Says:<br />
                        {{ comment.date | datetimeformat('%B %d, %Y, %I:%M%p')  }}
                    </span>
                    <span class="tools">
                        <a rel="nofollow" href="/comment/helpful/{{comment.id}}.html">This review was helpful</a> or
                        <a rel="nofollow" href="/comment/report/{{comment.id}}.html">Report abuse</a>
                    </span>
                    <div class="clear"></div>
                </div>

                <div class="text">{{comment.text}}</div>

                {% if comment.ratings() %}
                    <table class="ratings">
                        {% call macros.Ratings(comment.ratings()) %}
                        {% endcall %}
                    </table>
                {% endif %}
                <span class="comment-bottom"></span>
            </li>
        {% endfor %}
        <li class="comment">
    </ul>
</div>

{% include 'comment_form.html' %}

templates/footer.html
                </div>
            </div>
        <div id="footer">
            <span>&copy; 2009 Hosting Choice</span>
        </div>

        <script type="text/javascript">

            $('#errors').fadeIn(1500);
            $('#success').fadeIn(1500);

            $('.tools a').livequery(function() {
                var par = $(this).parent();

                $(this).ajaxify({
                    method: 'POST',
                    onComplete: function(opt) {
                        par.html('<strong>Thanks!</strong>');
                        par.fadeOut(5000, function() {
                            $(this).remove();
                            //par.parent().parent().remove();
                        });

                        if ($(this).attr('link').match('report')) {
                            var grand = $(par).parent().parent()
                            grand.fadeOut(1500, function() {
                                $(this).remove();
                            });
                        }
                    }
                });
            });

            $(document).ready(function() {
                var types = ['features', 'support', 'uptime']
                for (key in types) {
                    var name = 'id_rating_' + types[key];
                    var val_name = name+'_val'

                    var curvalue = $('#'+val_name).val()
                    if (curvalue < 0) {
                        curvalue = 0;
                    }

                    $('#'+name).rating(val_name, {maxvalue: 5, curvalue: curvalue});

                }

            });

            $('.comment').hover(
                function(){ $(this).find(".tools").show() },
                function(){ $(this).find(".tools").hide() });

        </script>
    </body>
</html>

templates/header.html
<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <title>{% block title %}Hosting Choice{% endblock %}</title>

        <link rel="stylesheet" href="/js/jquery/rating/rating.css" />
        <link rel="stylesheet" href="/css/style.css" />
        <script src="/js/jquery/jquery.js"></script>
        <script src="/js/jquery/rating/rating.js"></script>

        <script src="/js/jquery/ajaxify/jquery.livequery.pack.js" type="text/javascript"></script>
        <script src="/js/jquery/ajaxify/jquery.ajaxify.js" type="text/javascript"></script>
        <script src="/js/jquery/ajaxify/jquery.history.fixed.js" type="text/javascript"></script>
        <script src="/js/jquery/ajaxify/jquery.metadata.min.js" type="text/javascript"></script>
        <!--
        <script src="/static/js/jquery/ajaxify/jquery.simplemodal-1.1.1.js" type="text/javascript"></script>
        <script src="/static/js/jquery/ajaxify/animatedcollapse.js" type="text/javascript"></script>
        <script src="/static/js/jquery/ajaxify/flexigrid/flexigrid.js" type="text/javascript"></script>
        -->

    </head>
    <body>
        <div id="outer">
            <div id="inner">

                <div id="header">
                    <ul id="nav">
                        <li class="about"><a href="#about"><span>About Us</span></a></li>
                        <li class="reviews"><a href="#hosting"><span>Hosting Reviews</span></a></li>
                        <li class="submit"><a href="#submit"><span>Submit A Host</span></a></li>
                    </ul>
                </div>

templates/index.html
{% extends 'base.html' %}

{% block body %}
    Home
{% endblock %}

templates/leaderboard.html
{%- extends 'base.html' -%}

{%- block content -%}
    <h1>Top Web Hosts</h1>
    <p>Below you will find our list of the <strong>best web hosts</strong>. </p>

    {% call macros.Leaderboard(top_hosts) %}
    {% endcall %}
{%- endblock -%}

templates/macros.html
{%- macro Categories() -%}
    {{ caller() }}
{%- endmacro -%}

{%- macro get_rating_class(rating) -%}
    stars{{rating | smart_round | replace('.', '') }} {{ caller() }}
{%- endmacro -%}

{%- macro get_rating_mood(rating) -%}
    {%- if rating == -1 -%}
        unrated
    {%- elif rating < 1.67 -%}
        negative
    {%- elif rating > 3.3 -%}
        positive
    {%- else -%}
        neutral
    {%- endif %} {{ caller() }}
{%- endmacro -%}

{%- macro Ratings(ratings) -%}
    {% for name in ratings %}
    <tr>
        <th>{{name}}:</td>
        <td>
            <span class="
                {%- call get_rating_class(ratings[name]) %}stars{% endcall -%}
            "></span>
        </td>
    </tr>
    {% endfor %}
    {{ caller() }}
{%- endmacro -%}

{%- macro Features(features) -%}
    {% for feature in features %}
    <tr>
        <th>{{feature.type.name}}:</th>
        <td>
         {{feature.type.prefix}}{{feature.value}}{{feature.type.suffix}}
         </td>
     </tr>
    {% endfor %}
    {{ caller() }}
{%- endmacro -%}


{%- macro Leaderboard(hosts) -%}
    <table class="leaderboard">
        {% if hosts %}
            <tr>
                <th>#</th>
                <th>Rank</th>
                <th>Name</th>
                <th>Features</th>
            </tr>
            {% for host in hosts %}
            <tr class="{{ loop.cycle('odd', 'even') }}">
                    <td class="rank">{{ loop.index }}.</td>
                    <td>{{ host.percentage() }}%
                        <span>(<a href="/host/{{host.slug}}.html#comments">{{
                                host.comment_set.filter(active=1) | length }}
                                Reviews</a>)</span></td>
                    <td><a href="/host/{{host.slug}}.html">{{ host.name }}</a></td>
                    <td class="features">
                        {% for feature in host.feature_set.all() %}
                        <span><strong>{{feature.type.name}}:</strong>
                            {{feature.type.prefix}}{{feature.value}}{{feature.type.suffix}}
                        </span>
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            No Hosts!
        {% endif %}
    </table>
    {{ caller() }}
{%- endmacro -%}

templates/sidebar.html
<div id="sidebar">

    <h3>Top Rated Hosts</h3>
    <ul>
        {% for host in top_hosts %}
        <li><a href="/host/{{host.slug}}.html">{{host.name}}</a></li>
        {% endfor %}
    </ul>

    <h3>Recent Activity</h3>
    <ul>
        {% for review in recent_reviews %}
        <li>
        <a href="/host/{{review.host.slug}}.html">{{review.host.name}} Review</a>
        </li>
        {% endfor %}
    </ul>

    <h3>Site Links</h3>
    <ul>
        <li><a href="/submit.html">Submit A Host</a></li>
        <li><a href="/about.html">About Us</a></li>
    </ul>
</div>